Add initial `Linux` support
holepunchto/thread-stats pull request #2
Opened 2024-09-02 19:22 UTC by yassernasc

Calculation reference: https://stackoverflow.com/questions/16726779/how-do-i-get-the-total-cpu-usage-of-an-application-from-proc-pid-stat

Info parsing:
https://www.man7.org/linux/man-pages/man5/proc_uptime.5.html (get the whole system uptime)

https://www.man7.org/linux/man-pages/man5/proc_pid_task.5.html (get process child threads)

https://www.man7.org/linux/man-pages/man5/proc_pid_stat.5.html (get individual thread stats)

2024-09-03 08:45 UTC, kasperisager requested changes
Great first draft! In addition to the other points, we also write into quite a few buffers of varying sizes without really explaining and/or ensuring that the sizes are appropriate. You can probably get away with writing into a single buffer and then giving it a Sufficiently Large(tm) size of e.g. 4 or 8 KiB.

2024-09-03 08:45 UTC, kasperisager commented on linux.c
> +  *len = 0;
The initial value of `*len` is the size of `stats`, which we must ensure doesn't overflow in the loop further down. Track the number of written elements separately and only _after_ the loop assign this value to `*len`.

2024-09-03 08:45 UTC, kasperisager commented on binding.c
> +#include "linux.c"
```suggestion
#include "linux.h"
```

Only header files should be `#included`'ed so let's make it a header file.

2024-09-03 08:45 UTC, kasperisager commented on linux.c
> +  uptime_fd = open("/proc/uptime", O_RDONLY);
This should be `close()`'ed when no longer in use.

2024-09-03 08:45 UTC, kasperisager commented on linux.c
> +  self_task_dir = opendir(self_task_dir_path);
This should be `closedir()`'ed when no longer in use.

2024-09-03 08:45 UTC, kasperisager commented on linux.c
> +    stat_fd = open(stat_path, O_RDONLY);
This should be `close()`'ed when no longer in use.

2024-09-04 10:01 UTC, kasperisager requested changes

2024-09-04 10:01 UTC, kasperisager commented on linux.h
> +    return -1;
If this is hit then `uptime_fd` leaks. It should be closed prior to checking the read status.

2024-09-04 10:01 UTC, kasperisager commented on linux.h
> +  }
```suggestion
  err = close(uptime_fd);
  assert(err == 0);
```

Closing valid file descriptors is one of those things that aren't allowed to fail in practice so it's safe to assert to it succeeds.

2024-09-04 10:01 UTC, kasperisager commented on linux.h
> +    }
```suggestion
    err = close(stat_fd);
    assert(err == 0);
```

Same as above.

2024-09-04 10:01 UTC, kasperisager commented on linux.h
> +      continue;
Same as above; this risks leaking `stat_fd`.

2024-09-04 10:01 UTC, kasperisager commented on linux.h
> +  }
```suggestion
  err = closedir(self_task_dir);
  assert(err == 0);
```

Same as above.

2024-09-04 13:12 UTC, yassernasc commented on linux.h
> +    return -1;
Well pointed, leaks fixed at the new commit.

2024-09-04 13:30 UTC, kasperisager approved these changes
Looks solid! I made some small adjustments as well, should be good to go 🚀

2024-09-04 14:01 UTC, merged